# Generated by Django 4.2 on 2026-01-20 18:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=30)),
                ('scam_company_name', models.CharField(max_length=255)),
                ('amount_lost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('OTHER', 'Other')], max_length=10)),
                ('transfer_method', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('wire', 'Wire Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('last_transaction_date', models.DateField()),
                ('story', models.TextField(help_text='Describe how the scam occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
