# Generated by Django 4.2 on 2026-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='case_type',
            field=models.CharField(choices=[('romance_scam', 'Romance Scam'), ('crypto_scam', 'Cryptocurrency Scam'), ('investment_scam', 'Investment Scam'), ('bitcoin_scam', 'Bitcoin Scam'), ('forex_scam', 'Forex Scam'), ('online_shopping_scam', 'Online Shopping Scam'), ('identity_theft', 'Identity Theft'), ('impersonation_scam', 'Impersonation Scam'), ('other', 'Other')], default='romance_scam', max_length=50, verbose_name='Case Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='currency',
            field=models.CharField(choices=[('', 'Select Currency'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='transfer_method',
            field=models.CharField(choices=[('', 'Select Transfer Method Used'), ('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('wire', 'Wire Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20),
        ),
    ]
