# Generated by Django 4.2 on 2026-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_complaint_case_type_alter_complaint_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='transfer_method',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('wire', 'Wire Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20),
        ),
    ]
